import Head from 'next/head'
import { Sidebar } from 'app/components/Sidebar'
import { getAbout, getNavigation } from 'api/services/pages'
import { getSocials } from 'api/services/socials'
import { getRecentPostsSlugs, getPostBySlug } from 'api/services/posts'
import { Page, Post, Social } from 'commons/types'

export const getStaticPaths = async () => {
  const posts = await getRecentPostsSlugs()
  const paths = posts.map(slug => ({ params: { slug }}))
  console.log(paths)
  return {
    paths,
    fallback: 'blocking'
  }
}

export const getStaticProps = async ({params}: { params: { slug: string }}) => {
  console.log('Executing /blog/[slug] getStaticProps...', params.slug)
  const [ about, pages, post, socials ] = await Promise.all([
    getAbout(),
    getNavigation(),
    getPostBySlug(params.slug),
    getSocials(),
  ])

  return {
    props: {
      about,
      pages,
      post,
      socials,
    },
    redirect: 30 // em segundos
  }
}

interface Props {
  about: Page
  pages: readonly Page[]
  post: Post
  socials: Social[]
}

function AboutPage({about, post, socials}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row">
        <div className="col-md-9">
          <div dangerouslySetInnerHTML={{__html: post.content.html || ''}} />
        </div>
        <div className="col-md-3">
          <Sidebar about={about} socials={socials} />
        </div>
      </div>
    </>
  )
}

export default AboutPage
